import streamlit as st
import pandas as pd
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import random
import time

# --- CONFIGURATION ---
GLOBAL_PASSWORD = st.secrets["general"]["password"]
ADMIN_PASSWORD = st.secrets["general"]["admin_password"]

def get_client():
    scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
    creds_dict = dict(st.secrets["gcp_service_account"])
    creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
    return gspread.authorize(creds)

@st.cache_data(ttl=5)
def fetch_data(sheet_name):
    client = get_client()
    sheet = client.open("Kingshot_Data").worksheet(sheet_name)
    return sheet.get_all_records()

# --- AUTHENTICATION ---
if "password_correct" not in st.session_state:
    st.session_state["password_correct"] = False

if not st.session_state["password_correct"]:
    pw = st.text_input("Enter Alliance Password", type="password")
    if st.button("Login"):
        if pw == GLOBAL_PASSWORD:
            st.session_state["password_correct"] = True
            st.rerun()
        else:
            st.error("Wrong password")
    st.stop()

st.title("⚔️ Kingshot Vikings: Troop Swap")

try:
    roster_data = fetch_data("Roster")
    orders_data = fetch_data("Orders")
except Exception as e:
    st.error("Connection busy. Please wait 10 seconds and refresh.")
    st.stop()

# --- SIDEBAR: PLAYER ACTIONS ---
st.sidebar.header("Member Actions")
with st.sidebar.expander("Add/Update My Entry"):
    user = st.text_input("In-Game Username")
    status = st.radio("Status", ["Online", "Offline"])
    marches = st.slider("Marches to send", 4, 6, 5)
    
    if st.button("Submit Entry"):
        if user:
            with st.spinner("Saving..."):
                client = get_client()
                sheet = client.open("Kingshot_Data").worksheet("Roster")
                existing_idx = next((i for i, item in enumerate(roster_data) if item["Username"] == user), None)
                if existing_idx is not None:
                    sheet.delete_rows(existing_idx + 2)
                sheet.append_row([user, status, marches])
                st.cache_data.clear()
                st.success(f"Saved {user}!")
                time.sleep(1)
                st.rerun()

with st.sidebar.expander("❌ Remove My Entry"):
    del_user = st.text_input("Confirm Username to Remove")
    if st.button("Delete My Info"):
        with st.spinner("Removing..."):
            client = get_client()
            sheet = client.open("Kingshot_Data").worksheet("Roster")
            existing_idx = next((i for i, item in enumerate(roster_data) if item["Username"] == del_user), None)
            if existing_idx is not None:
                sheet.delete_rows(existing_idx + 2)
                st.cache_data.clear()
                st.success("Removed.")
                time.sleep(1)
                st.rerun()
            else:
                st.error("User not found.")

# --- MAIN AREA ---
tab1, tab2 = st.tabs(["Current Roster", "📜 SWAP ORDERS"])

with tab1:
    st.subheader(f"Registered Players: {len(roster_data)}")
    if roster_data:
        st.table(pd.DataFrame(roster_data).sort_values(by="Username"))
    else:
        st.info("Waiting for players to register...")

with tab2:
    if orders_data:
        st.header("📋 Alliance Swap Orders")
        st.write("Find your name in the **'From'** column to see where to send your marches.")
        df_disp = pd.DataFrame(orders_data).sort_values(by="From")
        st.table(df_disp)
    else:
        st.warning("Orders not yet generated by Admin.")

# --- ADMIN SECTION ---
st.markdown("---")
with st.expander("🛡️ Admin Controls"):
    admin_pw = st.text_input("Admin Password", type="password")
    
    if st.button("Generate & Publish Orders"):
        if admin_pw == ADMIN_PASSWORD:
            with st.spinner("Running Optimization Waterfall..."):
                if len(roster_data) < 2:
                    st.error("Need more players!")
                else:
                    # 1. Prepare Players
                    players = []
                    for p in roster_data:
                        players.append({
                            "Username": p["Username"],
                            "Status": p["Status"],
                            "Sends": int(p["Marches_Available"]),
                            "Receiving_Count": 0,
                            "History": [] # Tracks who they sent to
                        })
                    
                    # 2. Prepare Marches to be sent
                    marches_to_assign = []
                    for p in players:
                        for _ in range(p["Sends"]):
                            marches_to_assign.append(p)
                    
                    # Randomize to keep it fair, but sort so Online players get matched first
                    random.shuffle(marches_to_assign)
                    marches_to_assign.sort(key=lambda x: x['Status'] == 'Online', reverse=True)

                    final_orders = []

                    def find_best_target(sender, target_pool, max_cap):
                        # Filter for: Not me, has room, and NOT already in my history
                        eligible = [
                            t for t in target_pool 
                            if t['Username'] != sender['Username'] 
                            and t['Receiving_Count'] < max_cap 
                            and t['Username'] not in sender['History']
                        ]
                        if not eligible: return None
                        # Pick the one with the lowest receiving count to balance the load
                        eligible.sort(key=lambda x: x['Receiving_Count'])
                        return eligible[0]

                    # 3. DISTRIBUTION WATERFALL
                    for sender in marches_to_assign:
                        target = None
                        
                        # STEP A: Try Same Status (Cap 4)
                        target = find_best_target(sender, [p for p in players if p['Status'] == sender['Status']], 4)
                        
                        # STEP B: Try Cross Status (Cap 4)
                        if not target:
                            target = find_best_target(sender, players, 4)
                        
                        # STEP C: Try ANYONE (Cap 5) - The "Necessary" Step-up
                        if not target:
                            target = find_best_target(sender, players, 5)

                        # STEP D: Final Emergency (Ignore History if absolutely blocked)
                        if not target:
                             # This only happens in tiny groups with high march counts
                             emergency_pool = [t for t in players if t['Username'] != sender['Username'] and t['Receiving_Count'] < 6]
                             if emergency_pool:
                                 emergency_pool.sort(key=lambda x: x['Receiving_Count'])
                                 target = emergency_pool[0]

                        if target:
                            final_orders.append([sender['Username'], sender['Status'], target['Username'], target['Status']])
                            target['Receiving_Count'] += 1
                            sender['History'].append(target['Username'])
                        else:
                            final_orders.append([sender['Username'], sender['Status'], "MATH LIMIT REACHED", "N/A"])

                    # 4. Save to Sheets
                    df_final = pd.DataFrame(final_orders, columns=["From", "Status", "Send To", "Target Status"])
                    df_final = df_final.sort_values(by="From")

                    client = get_client()
                    order_sheet = client.open("Kingshot_Data").worksheet("Orders")
                    order_sheet.clear()
                    order_sheet.append_row(["From", "Status", "Send To", "Target Status"])
                    order_sheet.append_rows(df_final.values.tolist())
                    
                    st.cache_data.clear()
                    st.success("Orders published alphabetically with Status Priority!")
                    st.rerun()
        else:
            st.error("Wrong Admin Password")

    if st.button("Reset All Data"):
        if admin_pw == ADMIN_PASSWORD:
            with st.spinner("Wiping everything..."):
                client = get_client()
                client.open("Kingshot_Data").worksheet("Roster").clear()
                client.open("Kingshot_Data").worksheet("Roster").append_row(["Username", "Status", "Marches_Available"])
                client.open("Kingshot_Data").worksheet("Orders").clear()
                client.open("Kingshot_Data").worksheet("Orders").append_row(["From", "Status", "Send To", "Target Status"])
                st.cache_data.clear()
                st.success("Reset complete.")
                st.rerun()
